import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Lock, Save, Unlock } from "lucide-react";
import { api, ApiError } from "../api/client";
import type { AttendanceDay, AttendanceMatrixRow } from "../api/types";
import { Button, Field, Modal, Panel, StatusMessage } from "../components/Primitives";
import { MonthControl } from "../components/MonthControl";

type SelectedCell={employmentId:number;name:string;day:AttendanceDay;locked:boolean};
export function AdminAttendancePage(){
  const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const[search,setSearch]=useState("");const[selected,setSelected]=useState<SelectedCell|null>(null);const[confirmLock,setConfirmLock]=useState(false);const qc=useQueryClient();
  const key=["admin-attendance",month.getFullYear(),month.getMonth()+1];
  const query=useQuery({queryKey:key,queryFn:()=>api.admin<{year:number;month:number;rows:AttendanceMatrixRow[]}>(`/api/v1/admin/attendance/month?year=${month.getFullYear()}&month=${month.getMonth()+1}`)});
  const mutation=useMutation({mutationFn:({path,body}:{path:string;body:unknown})=>api.admin(path,{method:path.includes("lock")?"POST":"PUT",body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["admin-attendance"]});setSelected(null);setConfirmLock(false)}});
  const rows=(query.data?.rows??[]).filter(r=>`${r.user_name} ${r.employment_label}`.toLowerCase().includes(search.toLowerCase()));const days=rows[0]?.days??[];
  const lock=()=>selected&&mutation.mutate({path:`/api/v1/admin/attendance/${selected.locked?"unlock":"lock"}`,body:{employment_id:selected.employmentId,year:month.getFullYear(),month:month.getMonth()+1}});
  return <div className="page"><header className="page-heading"><div><p>Kontrola skutečně odpracovaného času</p><h1>Docházkové listy</h1></div><MonthControl value={month} onChange={setMonth}/></header><Panel><div className="toolbar"><Field label="Filtrovat úvazky"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Jméno nebo úvazek"/></Field><span className="badge">{rows.length} úvazků</span></div>{query.isPending?<div className="panel-body"><StatusMessage kind="loading" title="Sestavuji měsíční matici"/></div>:query.error?<div className="panel-body"><StatusMessage kind="error" title="Docházku nelze načíst">{query.error.message}</StatusMessage></div>:rows.length===0?<div className="panel-body"><StatusMessage kind="empty" title="Pro filtr nejsou žádné úvazky"/></div>:<div className="data-table-wrap"><table className="data-table matrix"><thead><tr><th>Zaměstnanec / úvazek</th>{days.map(day=><th key={day.date}>{new Date(`${day.date}T12:00`).getDate()}.</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.employment_id} className={row.is_active_in_month?"":"inactive"}><td><button className="row-action" onClick={()=>setSelected({employmentId:row.employment_id,name:row.employment_label,day:row.days[0],locked:row.locked})}>{row.user_name}</button><br/><small>{row.employment_title} · {row.employment_type}</small>{row.locked&&<span className="locked"> · zámek</span>}</td>{row.days.map(day=><td className="day-cell" key={day.date}><button aria-pressed={selected?.employmentId===row.employment_id&&selected.day.date===day.date} onClick={()=>setSelected({employmentId:row.employment_id,name:row.employment_label,day,locked:row.locked})}>{day.planned_status?<span className="cell-status">{day.planned_status}</span>:<>{day.arrival_time??"–"}<br/>{day.departure_time??"–"}</>}</button></td>)}</tr>)}</tbody></table></div>}</Panel>{selected&&<Panel title={`${selected.name} · ${selected.day.date}`}><AttendanceInspector selected={selected} pending={mutation.isPending} onSave={(arrival,departure)=>mutation.mutate({path:"/api/v1/admin/attendance",body:{employment_id:selected.employmentId,date:selected.day.date,arrival_time:arrival||null,departure_time:departure||null}})} onLock={()=>setConfirmLock(true)}/></Panel>}{mutation.error&&<StatusMessage kind="error" title="Operaci nelze dokončit">{mutation.error.message}</StatusMessage>}{confirmLock&&selected&&<Modal title={selected.locked?"Odemknout měsíc?":"Uzamknout měsíc?"} description={`${selected.name} · ${month.getMonth()+1}/${month.getFullYear()}. ${selected.locked?"Po odemknutí bude možné záznamy měnit.":"Po uzamčení budou záznamy pouze pro čtení."}`} confirmLabel={selected.locked?"Odemknout":"Uzamknout"} onClose={()=>setConfirmLock(false)} onConfirm={lock}/>}</div>
}

function AttendanceInspector({selected,pending,onSave,onLock}:{selected:SelectedCell;pending:boolean;onSave:(a:string,d:string)=>void;onLock:()=>void}){const[arrival,setArrival]=useState(selected.day.arrival_time??"");const[departure,setDeparture]=useState(selected.day.departure_time??"");return <div className="panel-body"><div className="form-grid"><Field label="Příchod"><input type="time" disabled={selected.locked} value={arrival} onChange={e=>setArrival(e.target.value)}/></Field><Field label="Odchod"><input type="time" disabled={selected.locked} value={departure} onChange={e=>setDeparture(e.target.value)}/></Field><Field label="Plánovaný příchod"><input disabled value={selected.day.planned_arrival_time??"—"}/></Field><Field label="Plánovaný odchod"><input disabled value={selected.day.planned_departure_time??"—"}/></Field></div><div className="action-row"><Button variant="quiet" onClick={onLock}>{selected.locked?<Unlock/>:<Lock/>}{selected.locked?"Odemknout měsíc":"Uzamknout měsíc"}</Button><Button disabled={pending||selected.locked} onClick={()=>onSave(arrival,departure)}><Save/>Uložit den</Button></div></div>}

type PlanMonth={year:number;month:number;selected_employment_ids:number[];available_employments:any[];rows:Array<{employment_id:number;user_name:string;title:string;employment_type:string;display_label:string;days:any[]}>};
export function AdminShiftPlanPage(){
  const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const[selected,setSelected]=useState<{row:any;day:any}|null>(null);const[selection,setSelection]=useState<number[]|null>(null);const[conflict,setConflict]=useState<Record<string,unknown>|null>(null);const qc=useQueryClient();const key=["shift-plan",month.getFullYear(),month.getMonth()+1];
  const query=useQuery({queryKey:key,queryFn:()=>api.admin<PlanMonth>(`/api/v1/admin/shift-plan?year=${month.getFullYear()}&month=${month.getMonth()+1}`)});
  const mutation=useMutation({mutationFn:(body:Record<string,unknown>)=>api.admin("/api/v1/admin/shift-plan",{method:"PUT",body:JSON.stringify(body)}),onSuccess:()=>{qc.invalidateQueries({queryKey:["shift-plan"]});setSelected(null);setConflict(null)},onError:(error,body)=>{if(error instanceof ApiError&&error.conflict&&body.status)setConflict(body)}});
  const selectionMutation=useMutation({mutationFn:(employmentIds:number[])=>api.admin("/api/v1/admin/shift-plan/selection",{method:"PUT",body:JSON.stringify({year:month.getFullYear(),month:month.getMonth()+1,employment_ids:employmentIds})}),onSuccess:()=>{qc.invalidateQueries({queryKey:["shift-plan"]});setSelection(null)}});
  const rows=query.data?.rows??[];const days=rows[0]?.days??[];
  const activeSelection=selection??query.data?.selected_employment_ids??[];const toggle=(id:number,checked:boolean)=>setSelection(checked?[...activeSelection,id]:activeSelection.filter(item=>item!==id));
  return <div className="page"><header className="page-heading"><div><p>Budoucí kapacita a stav dne</p><h1>Plán služeb</h1></div><MonthControl value={month} onChange={value=>{setMonth(value);setSelection(null);setSelected(null)}}/></header>{query.data&&<Panel title="Úvazky zahrnuté do měsíce" actions={<Button disabled={selection===null||selectionMutation.isPending} onClick={()=>selectionMutation.mutate(activeSelection)}><Save/>Uložit výběr</Button>}><div className="selection-grid">{query.data.available_employments.map((item:any)=><label key={item.id} className="choice-card"><input type="checkbox" checked={activeSelection.includes(item.id)} onChange={event=>toggle(item.id,event.target.checked)}/><span><strong>{item.display_label??item.label}</strong><small>{item.employment_type} · {item.start_date} — {item.end_date??"bez konce"}</small></span></label>)}</div></Panel>}<Panel>{query.isPending?<div className="panel-body"><StatusMessage kind="loading" title="Načítám plán služeb"/></div>:query.error?<div className="panel-body"><StatusMessage kind="error" title="Plán nelze načíst">{query.error.message}</StatusMessage></div>:rows.length===0?<div className="panel-body"><StatusMessage kind="empty" title="Pro tento měsíc není vybrán žádný úvazek">Vyberte alespoň jeden úvazek v panelu nad maticí.</StatusMessage></div>:<div className="data-table-wrap"><table className="data-table matrix"><thead><tr><th>Zaměstnanec / úvazek</th>{days.map(day=><th key={day.date}>{new Date(`${day.date}T12:00`).getDate()}.</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.employment_id}><td><strong>{row.user_name}</strong><br/><small>{row.title} · {row.employment_type}</small></td>{row.days.map((day:any)=><td className="day-cell" key={day.date}><button aria-pressed={selected?.row.employment_id===row.employment_id&&selected.day.date===day.date} onClick={()=>setSelected({row,day})}>{day.status?<span className="cell-status">{day.status}</span>:<>{day.arrival_time??"–"}<br/>{day.departure_time??"–"}</>}</button></td>)}</tr>)}</tbody></table></div>}</Panel>{selected&&<PlanInspector selected={selected} pending={mutation.isPending} onSave={(arrival,departure,status)=>mutation.mutate({employment_id:selected.row.employment_id,date:selected.day.date,arrival_time:arrival||null,departure_time:departure||null,status:status||null,confirm_delete_conflicts:false})}/>} {(mutation.error||selectionMutation.error)&&!conflict&&<StatusMessage kind="error" title="Plán nelze uložit">{(mutation.error??selectionMutation.error)?.message}</StatusMessage>}{conflict&&<Modal title="Nahradit existující údaje stavem dne?" description="Zvolený celodenní stav je v konfliktu s evidovanou docházkou nebo časovým plánem. Potvrzením budou konfliktní hodnoty odstraněny." confirmLabel="Nahradit údaje" danger onClose={()=>setConflict(null)} onConfirm={()=>mutation.mutate({...conflict,confirm_delete_conflicts:true})}/>}</div>
}
function PlanInspector({selected,pending,onSave}:{selected:{row:any;day:any};pending:boolean;onSave:(a:string,d:string,s:string)=>void}){const[a,setA]=useState(selected.day.arrival_time??"");const[d,setD]=useState(selected.day.departure_time??"");const[s,setS]=useState(selected.day.status??"");return <Panel title={`${selected.row.display_label} · ${selected.day.date}`}><div className="panel-body form-grid"><Field label="Začátek"><input type="time" value={a} disabled={!!s} onChange={e=>setA(e.target.value)}/></Field><Field label="Konec"><input type="time" value={d} disabled={!!s} onChange={e=>setD(e.target.value)}/></Field><Field label="Celodenní stav"><select value={s} onChange={e=>setS(e.target.value)}><option value="">Pracovní den</option><option value="HOLIDAY">Dovolená</option><option value="OFF">Volno</option></select></Field><div className="action-row"><Button disabled={pending} onClick={()=>onSave(a,d,s)}><Save/>Uložit plán</Button></div></div></Panel>}
