import { FormEvent, useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CloudCog, LogOut, UserRound } from "lucide-react";
import { api, ApiError } from "../api/client";
import type { AttendanceDay, PortalSession } from "../api/types";
import { Brand } from "../components/Brand";
import { Button, Field, Modal, StatusMessage } from "../components/Primitives";
import { MonthControl } from "../components/MonthControl";
import { clearPortalSession, loadPortalSession, savePortalLogin, selectEmployment } from "../state/portalSession";
import { flushOperations, listOperations, queueOperation } from "../state/offlineQueue";

const dayName = new Intl.DateTimeFormat("cs-CZ", { weekday:"short", timeZone:"Europe/Prague" });
const fullDate = new Intl.DateTimeFormat("cs-CZ", { day:"numeric", month:"long", timeZone:"Europe/Prague" });
const durationMinutes=(start:string|null,end:string|null)=>{if(!start||!end)return 0;const[sh,sm]=start.split(":").map(Number);const[eh,em]=end.split(":").map(Number);return Math.max(0,eh*60+em-(sh*60+sm))};
const hoursLabel=(minutes:number)=>`${Math.floor(minutes/60)} h ${minutes%60} min`;

function EmployeeLogin({ onLogin }: { onLogin:(session:PortalSession)=>void }) {
  const [email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[pending,setPending]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setPending(true);setError("");try{onLogin(savePortalLogin(await api.portalLogin(email,password)))}catch(err){setError(err instanceof Error?err.message:"Přihlášení se nezdařilo.")}finally{setPending(false)}};
  return <main className="auth-page"><section className="auth-story"><Brand/><div><h1>Vaše směna.<span>Váš přehled.</span></h1><p>Zapište příchod a odchod, porovnejte plán a mějte celý měsíc pod kontrolou i při dočasném výpadku připojení.</p></div><small>Bezpečný zaměstnanecký portál</small></section><section className="auth-board"><div className="auth-card"><h2>Přihlášení zaměstnance</h2><p>Použijte svůj pracovní e-mail a osobní heslo.</p><form onSubmit={submit}><Field label="Pracovní e-mail"><input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Heslo"><input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field>{error&&<StatusMessage kind="error" title="Přístup nebyl povolen">{error}</StatusMessage>}<Button disabled={pending}>{pending?"Ověřuji…":"Otevřít docházku"}</Button></form></div></section></main>;
}

function DayCard({ day, locked, onSave, onStatus }: { day:AttendanceDay;locked:boolean;onSave:(day:AttendanceDay,arrival:string,departure:string)=>void;onStatus:(day:AttendanceDay,status:string)=>void }) {
  const [arrival,setArrival]=useState(day.arrival_time??"");const[departure,setDeparture]=useState(day.departure_time??"");
  useEffect(()=>{setArrival(day.arrival_time??"");setDeparture(day.departure_time??"")},[day]);
  const date=new Date(`${day.date}T12:00:00`);const dirty=arrival!==(day.arrival_time??"")||departure!==(day.departure_time??"");
  return <article className={`ledger-day ${!day.is_within_employment_period?"ledger-day--outside":""}`}><header><strong>{date.getDate()}</strong><span>{dayName.format(date)}</span></header><select aria-label={`${fullDate.format(date)} stav dne`} value={day.planned_status??""} disabled={locked||!day.is_within_employment_period} onChange={e=>onStatus(day,e.target.value)}><option value="">Pracovní den</option><option value="HOLIDAY">Dovolená</option><option value="OFF">Volno</option></select>{!day.planned_status&&<div className="ledger-day__times"><input aria-label={`${fullDate.format(date)} příchod`} type="time" value={arrival} disabled={locked||!day.is_within_employment_period} onChange={e=>setArrival(e.target.value)}/><input aria-label={`${fullDate.format(date)} odchod`} type="time" value={departure} disabled={locked||!day.is_within_employment_period} onChange={e=>setDeparture(e.target.value)}/></div>}<footer><span>{day.planned_arrival_time||day.planned_departure_time?`Plán ${day.planned_arrival_time??"–"}–${day.planned_departure_time??"–"}`:"Bez plánu"}</span>{dirty&&!day.planned_status&&<button onClick={()=>onSave(day,arrival,departure)}>Uložit</button>}</footer></article>;
}

export function EmployeePage(){
  const[session,setSession]=useState<PortalSession|null>(()=>loadPortalSession());const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const[queueCount,setQueueCount]=useState(0);const[notice,setNotice]=useState("");const[statusConflict,setStatusConflict]=useState<{day:AttendanceDay;status:string}|null>(null);const qc=useQueryClient();
  const employmentId=session?.selected_employment_id??null;
  const query=useQuery({queryKey:["attendance",employmentId,month.getFullYear(),month.getMonth()+1],queryFn:()=>api.attendance(employmentId!,month.getFullYear(),month.getMonth()+1),enabled:!!employmentId,retry:false});
  useEffect(()=>{listOperations().then(items=>setQueueCount(items.length));const allowed=new Set(session?.available_employments.map(item=>item.id)??[]);const online=()=>flushOperations(allowed).then(async result=>{setQueueCount((await listOperations()).length);if(result.completed)setNotice(`Synchronizováno operací: ${result.completed}.`);if(result.blocked)setNotice(`Synchronizace čeká na vyřešení: ${result.blocked.last_error}`);qc.invalidateQueries({queryKey:["attendance"]})});window.addEventListener("online",online);return()=>window.removeEventListener("online",online)},[qc,session]);
  const mutation=useMutation({mutationFn:async({day,arrival,departure}:{day:AttendanceDay;arrival:string;departure:string})=>{const payload={employment_id:employmentId,date:day.date,arrival_time:arrival||null,departure_time:departure||null};try{await api.saveAttendance(payload);return{saved:true,queued:false}}catch(error){if(error instanceof ApiError&&error.offline){await queueOperation({kind:"attendance",employment_id:employmentId!,payload});setQueueCount((await listOperations()).length);return{saved:false,queued:true}}throw error}},onSuccess:result=>{if(result.queued){setNotice("Změna čeká v bezpečné frontě na obnovení připojení.");return}qc.invalidateQueries({queryKey:["attendance"]});setNotice("Docházka byla uložena.")}});
  const statusMutation=useMutation({mutationFn:async({day,status,confirmed=false}:{day:AttendanceDay;status:string;confirmed?:boolean})=>{const payload={employment_id:employmentId,date:day.date,status:status||null,confirm_delete_conflicts:confirmed};try{await api.savePortalStatus(payload);return{saved:true,queued:false,conflict:false}}catch(error){if(error instanceof ApiError&&error.offline){await queueOperation({kind:"day-status",employment_id:employmentId!,payload});setQueueCount((await listOperations()).length);return{saved:false,queued:true,conflict:false}}if(error instanceof ApiError&&error.conflict&&!confirmed){setStatusConflict({day,status});return{saved:false,queued:false,conflict:true}}throw error}},onSuccess:result=>{if(result.queued){setNotice("Stav dne čeká ve frontě na synchronizaci.");return}if(result.saved){setStatusConflict(null);qc.invalidateQueries({queryKey:["attendance"]});setNotice("Stav dne byl uložen.")}}});
  if(!session)return <EmployeeLogin onLogin={setSession}/>;
  const logout=()=>{clearPortalSession();setSession(null)};
  return <div className="employee-app"><header className="topbar"><Brand compact/><span>{session.display_name}</span><Button variant="quiet" onClick={logout}><LogOut/>Odhlásit</Button></header><main id="main-content"><div className="page"><header className="page-heading"><div><p>Zaměstnanecký portál</p><h1>Měsíční docházka</h1></div><div className="page-actions"><span className={`badge ${navigator.onLine?"badge--good":"badge--warn"}`}>{navigator.onLine?"Online":"Offline"}</span>{queueCount>0&&<span className="badge badge--warn"><CloudCog/>Čeká {queueCount}</span>}</div></header><PanelToolbar session={session} onSession={setSession} month={month} onMonth={setMonth}/>{notice&&<StatusMessage kind={queueCount?"offline":"success"} title={queueCount?"Změna je ve frontě":"Hotovo"}>{notice}</StatusMessage>}{(mutation.error||statusMutation.error)&&<StatusMessage kind="error" title="Změnu nelze uložit">{(mutation.error||statusMutation.error)?.message}</StatusMessage>}{query.isPending&&<StatusMessage kind="loading" title="Načítám docházku"/>}{query.error&&<StatusMessage kind="error" title="Docházku nelze načíst">{query.error.message}</StatusMessage>}{query.data&&<><div className="metrics"><div className="metric"><span>Úvazek</span><strong><UserRound/></strong><small>{query.data.employment_label}</small></div><div className="metric"><span>Odpracováno</span><strong>{hoursLabel(query.data.days.reduce((total,day)=>total+durationMinutes(day.arrival_time,day.departure_time),0))}</strong><small>{query.data.days.filter(day=>day.arrival_time||day.departure_time).length} vyplněných dnů</small></div><div className="metric"><span>Naplánováno</span><strong>{hoursLabel(query.data.days.reduce((total,day)=>total+durationMinutes(day.planned_arrival_time,day.planned_departure_time),0))}</strong><small>{query.data.days.filter(day=>day.planned_status).length} celodenních stavů</small></div><div className="metric"><span>Stav období</span><strong>{query.data.locked?"Zámek":"Otevřeno"}</strong><small>{query.data.locked?"jen pro čtení":"lze zapisovat"}</small></div></div>{query.data.locked&&<StatusMessage kind="offline" title="Měsíc je uzamčen">Záznamy jsou dostupné pouze pro čtení.</StatusMessage>}<section className="ledger" aria-label="Dny měsíce">{query.data.days.map(day=><DayCard key={day.date} day={day} locked={query.data.locked} onSave={(d,a,p)=>mutation.mutate({day:d,arrival:a,departure:p})} onStatus={(d,status)=>statusMutation.mutate({day:d,status})}/>)}</section></>}{statusConflict&&<Modal title="Změnit stav dne a odstranit kolidující data?" description={`Den ${statusConflict.day.date} obsahuje docházku nebo plán, který se zvoleným stavem koliduje.`} confirmLabel="Změnit stav a odstranit konflikty" danger onClose={()=>setStatusConflict(null)} onConfirm={()=>statusMutation.mutate({...statusConflict,confirmed:true})}/>}</div></main></div>;
}

function PanelToolbar({session,onSession,month,onMonth}:{session:PortalSession;onSession:(s:PortalSession)=>void;month:Date;onMonth:(d:Date)=>void}){return <div className="panel toolbar"><Field label="Aktivní úvazek"><select value={session.selected_employment_id??""} onChange={e=>onSession(selectEmployment(session,Number(e.target.value)))}>{session.available_employments.map(e=><option key={e.id} value={e.id}>{e.label??`${e.title} · ${e.employment_type}`}</option>)}</select></Field><MonthControl value={month} onChange={onMonth}/><span className="badge badge--good"><CalendarDays/>Pražský čas</span></div>}
